apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: Backend_App

  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /healthz
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'

spec:
  ingressClassName: alb

  rules:
    - http:
        paths:
          # FRONTEND
          - path: /
            pathType: Prefix
            backend:
              service:
                name: Frontend_App-service
                port:
                  number: 80

          # BACKEND
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: Backend_App-service
                port:
                  number: 80
